# =========================
# Paramètres du site
# =========================
title: "Andile Boussari"
email: andileboussari@gmail.com
description: >-
  Portfolio professionnel d'Andile Boussari : labs techniques, projets en
  administration systèmes & réseaux et cybersécurité.
twitter_username: ""
github_username: andile-boussari
minimal_mistakes_skin: 'air'
search: true

# Langue du site
lang: "fr"

# Adresse du site
url: "https://andile-boussari.github.io"
baseurl: ""   # IMPORTANT : vide, comme ici

# Build
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# ajout teaser
teaser: true

excerpt_separator: "<!--more-->"

# Sortie des URLs
permalink: /:categories/:title/

# Pagination pour les posts sur la page d'accueil
paginate: 5
paginate_path: /page:num/

# Fuseau horaire
timezone: Europe/Paris

# On inclut les pages perso
include:
  - _pages

# Plugins (doivent correspondre à ceux fournis par GitHub Pages + doc Minimal Mistakes)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
  - jemoji
  - jekyll-include-cache


# Auteur
author:
  name   : "Andile Boussari"
  avatar : "/assets/images/bio-photo.jpg"
  bio: |
    - Administrateur systèmes & réseaux
    - Cybersécurité
    - Passionné de labs & veille technologique.
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Andile-Boussari"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andile-boussari"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:andileboussari@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Andile-Boussari"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andile-boussari"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:andileboussari@gmail.com"

# Valeurs par défaut
defaults:
  - scope:
      path: ""
    values:
      lang: fr
  # Articles (_posts)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      read_time: true
      comments: true
      share: false
      show_date: true
      related: false

  # Pages (_pages)
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
